name: qimendunjia
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.2
  tuple: ^2.0.2
#  chinese_lunar_calendar: ^0.0.13
  tyme: ^1.4.1
  intl: ^0.20.2
  meta: 1.18.1
  collection: ^1.19.1
  google_fonts: ^8.0.0
  lottie: ^3.3.2
  board_datetime_picker: 2.8.5
  sliding_switch: ^1.1.0
  slide_switcher: ^1.1.2
  animated_read_more_text: ^0.0.6
  aura_box: ^1.0.2

  provider: ^6.1.5+1
  common:
    git:
      url: https://github.com/weijingtai/xuan-common.git
      ref: main
  dotlottie_loader: ^0.0.5
  auto_size_text: ^3.0.0
  flutter_sliding_toast: ^1.5.3
  json_serializable: ^6.12.0
  json_annotation: ^4.10.0
  flutter_animate: 4.5.2
  animated_custom_dropdown: ^3.1.1
  flutter_shakemywidget: ^1.0.5+1
  # flutter_web_plugins:
    # sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
    - assets/qi_men_dun_jia/
    - assets/lotties/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
